# Generated by Django 3.2.4 on 2021-08-25 07:02

from django.db import migrations, models
import logapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to=logapp.models.nameFile, verbose_name='file_uploaded')),
                ('name', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
    ]
